version: '3'

services:
  nginx:
    env_file:
      - .env
    image: nginx:latest
    container_name: nginx
    hostname: ghost-nginx
    ports:
      - 80:8081
    volumes:
      - ./nginx/conf/ghost.conf:/etc/nginx/conf.d/ghost.conf:z
    links:
      - ghost
    restart: always

  ghost:
    env_file:
      - .env
    image: ghost:latest
    container_name: ghost
    hostname: ghost
    volumes:
      - $PWD/ghost/volumes/config.production.json:/var/lib/ghost/config.production.json:z #overwrite default settings 
      - ./ghost/content:/var/lib/ghost/content:z
    expose:
    - "3306"
    environment: # this section can be commented to start in dev mode by default
      - NODE_ENV=${NODE_ENV} # set either production or development, then it will load the respective config
    restart: always
    links:
      - mysql

  mysql:
    env_file:
      - .env
    image: mysql:latest
    container_name: mysql
    volumes:
       - ./dbdata:/var/lib/mysql:z  # Persist storage
    expose:
      - "3306"
    environment:
      # Beware of special characters in password that can be interpreted by shell
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} #specify your root pass
      - MYSQL_DATABASE=${MYSQL_DATABASE} #hostdata
      - MYSQL_USER=${MYSQL_USER} #ghostusr
      - MYSQL_PASSWORD=${MYSQL_PASSWORD} #please change this
    restart: always
